#!/bin/bash
python3 -m unittest unittests tests.backup.backupConfigurationParserTests tests.backup.btrfsSnapshottingTests tests.backup.obsoleteSnapshotsDeterminationTests tests.periodicStatusReportTests tests.emailNotificationTests tests.dataConsistencyTests tests.packageSystemTests tests.integration.integrationTests
